### ISSUE TITLE
Support js/css file versioning

### ISSUE THREAD

**Issue by hlorofos** [philicevic/mix-html-builder#1]
is there any way to apply versions from `mix-manifest.json` to the files referred from html?

**Comment by philicevic** [comment]
Do you have an explicit example of what you want to do?

Sorry for the late answer, i've been a bit inactive in the past weeks.

**Comment by hlorofos** [comment]
@philicevic 
here is the example how I did it to illustrate my goals:
```
//add versions to names of scripts, stylesheets, images at html
const addVersions = fileNames => {
    const manifest = JSON.parse(fs.readFileSync('public/mix-manifest.json'));

    for (let i = 0; i < fileNames.length; i++) {
        let innerHtml = fs.readFileSync(fileNames[i]).toString();

        Object.entries(manifest).forEach(([key, value]) => {
            innerHtml = innerHtml.replace(key, value);
        });

        fs.writeFileSync(fileNames[i], innerHtml);
        console.log(`Done adding versions to ${fileNames[i]}\n`);
    }
};
```

**Comment by philicevic** [comment]
At the moment I don't really see a need for this in this package, if I am not getting you wrong.

That is because I don't see a real use case for applying a version number to an asset.

**Comment by goaround** [comment]
Hi @philicevic,

I just discovered your package and would find this quite helpful to use `mix.version()` if `inject: true` for cache busting.

Instead of `<link href="public/dist/app.css" rel="stylesheet">` it would take the hash from `mix-manifest.json` and add it to the url `<link href="public/dist/app.css?id=a23eafd3d4d86790fc00" rel="stylesheet">`

@hlorofos where did you add your function?

**Comment by philicevic** [comment]
I tried a few things out now but I'm not really sure how to do this yet.
The assets get injected by HtmlWebpackPlugin and I have not found a way to overwrite the injected filepaths yet.

The snippet of @hlorofos certainly should do the right thing, but it needs to be some kind of post-run script, because it only replaces the old values.

**Comment by philicevic** [comment]
I'm thinking if we really need to use mix for that?
What benefits do we have from using `mix.version()` instead of the built-in `hash` option of `HtmlWebpackPlugin`.
Would be much easier to handle I think.

**Comment by goaround** [comment]
@philicevic should work as well. Looking forward for the new version with the `postHtmlConfig` option

**Comment by goaround** [comment]
@philicevic I tried the new Version with the follow config:

```
mix.html({
	output: 'public',
	inject: true,
	postHtmlConfig: {
		versioning: true,
	}
});
```

But my Script/Styles still look the same:

```
<script src="/public/dist/app.js"></script>
```

Could you give it a try?

**Comment by goaround** [comment]
Sorry got it wrong. This works:

```
mix.html({
	output: 'public',
	inject: true,
	versioning: true,
});
```

**Comment by kgtm** [comment]
@goaround Is it possible to use versioning without inject?

**Comment by goaround** [comment]
@kgtm I don't think so.
