### ISSUE TITLE
Passing variables inside extends

### ISSUE THREAD

**Issue by weblabio** [philicevic/mix-html-builder#19]
Is it possible to pass variables to an extensible template? 
similar to how this is done in include

_home.html_
```html
<extends src="app" locals='{
    "pageTitle": "Home",
    "pageClass": "page-home",
}'>
    ...
</extends>
```

_layouts/app.html_
```html
<head>
     <title>{{ pageTitle }}</title>
</head>
<body class="{{ pageClass }}">
....
</body>
```

otherwise the **extends** functionality does not make sense, since the expandable part into reality can almost never be static

**Comment by philicevic** [comment]
I'm not quite sure if it is possible or not, because we're depending on `posthtml-extend`. If I'll somehow be able make it work using their `plugins` option, I'll try to add it.

The extend functionality can make sense. It depends on the way you're using it. In your case it's obviously a problem that you cannot pass data.

**Comment by philicevic** [comment]
[This pull request](https://github.com/posthtml/posthtml-extend/pull/36) will make this possible. Waiting for it to get merged.
