### ISSUE TITLE
 Error: Child compilation failed

### ISSUE THREAD

**Issue by nepster-web** [philicevic/mix-html-builder#26]
I have main html file, and I include _footer.html

main.html
```
...
<include src="./_footer.html"></include>
...
```

_footer.html:
```
...
<img src="./images/icons/phone.svg" alt="phone">
...
```

so, I see next errors:

![изображение](https://user-images.githubusercontent.com/5681979/101993817-498b7700-3cc6-11eb-9100-045fbad3ebe4.png)

why it happens ?

**Comment by philicevic** [comment]
Are you sure that the images are at the place where webpack expects them to be?

**Comment by nepster-web** [comment]
no, there are no pictures in _sections folder.

My structure looks like this:

public 
  - images
  - index.html
  
src 
 - scss
 - html
   - _sections
      - _footer.html
   - index.html


I don't need additional processing for images, so the images are in folder public/images/...

**Comment by philicevic** [comment]
I tried to recreate it and got the same error. You should be able to fix it by using `/images/icons/phone.svg` instead of `./images/icons/phone.svg`. This forces webpack to just paste the absolute path instead of searching for the file.

I don't know if it really is the best solution, but in your case it should be working.
The way webpack works i don't think i can do something about it anyway.

**Comment by nepster-web** [comment]
until now I have not used a web server. apparently need to connect

thank you very much.
