### ISSUE TITLE
Unable to compile files

### ISSUE THREAD

**Issue by me-awesome** [philicevic/mix-html-builder#31]
Hi,

I include the extension and try to build the files but if I am placing extends an try to include files or blocks or slot/fills that are not compiling.

`master.html`
```
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="author" content="Awesome9">
		<title><slot name="title">· TEMPLATE_NAME</slot></title>
	</head>

	<body>

		<main class="container">

			<slot name="content"></slot>

		</main><!-- /.container -->

	</body>

</html>
```

`index.html`
```
<extends src="master.html">

	<fill name="title">Page title</fill>

	<fill name="content">
		<p>sssssssssssssssss</p>
	</fill>

	<include src="button.html" locals='{
        "text": "Button"
    }'></include>

</extends>
```

**Output**
```
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<meta name="author" content="Awesome9">
		<title><slot name="title">· TEMPLATE_NAME</slot></title>
	</head>

	<body>

		<main class="container">

			<slot name="content"></slot>

		</main>

	</body>

</html>

```

**Comment by me-awesome** [comment]
@philicevic can you please help me with this

**Comment by philicevic** [comment]
Sorry for the late answer, you probably worked this out already.

You are using `slot` and `fill` as tag names for the passed content. But you need to use `block` as mentioned in the [docs](https://github.com/philicevic/mix-html-builder#extend-layouts).

However, as I was testing this, it turns out there is an [issue with posthtml-parser](https://github.com/posthtml/posthtml-parser/issues/53) that makes it impossible to put a block into a title tag.
